const map = [
    "WWWWWWWWWWWWWWWWWWWWW",
    "W   W     W     W W W",
    "W W W WWW WWWWW W W W",
    "W W W   W     W W   W",
    "W WWWWWWW W WWW W W W",
    "W         W     W W W",
    "W WWW WWWWW WWWWW W W",
    "W W   W   W W     W W",
    "W WWWWW W W W WWW W W",
    "S     W W W W W W WWW",
    "WWWWW W W W W W W W W",
    "W       W W   W W W W",
    "W WWWWWWW WWWWW W W W",
    "W       W       W   W",
    "W WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W  W   W                                W",
    "W      WWWWWWWW                         W",
    "WWWWWW         WWWWWWWWWWWWWWWWWFWWWWWWWW",
    "W    WWWWWWW  WWW   W                   W",
    "W               WWWWWWWWWWWWWWWWWWWWWWW W",
    "W  WWWWWWWWWWWWWW                       W",
    "W               W     WWWWWWWWWWWWWWWWWWWW",
    "W WWWWWWWWWWWWWW    WW",
    "W         W          W",
    "W         WWWWWWW  WWW",
    "WWWWWWWW             W",
    "       WWWWWWWWWWWWWWW",
]